spring:
  application:
    name: offer-aggregator-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:migrations/db.changelog-master.yaml
api:
  v1: api/v1
logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
  level:
    web: debug

product-config:
  financing-institutions:
    FastBank:
        enabled: true
        url: https://shop.stage.klix.app/api/FastBank
    SolidBank:
        enabled: true
        url: https://shop.stage.klix.app/api/SolidBank