spring:
  application:
    name: offer-aggregator-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:migrations/db.changelog-master.yaml
api:
  v1: api/v1
logging:
  pattern:
    correlation: "[%X{traceId:-},%X{spanId:-}] "
  level:
#    web: debug
    lv.klix.oas.integration: debug
management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus
aes:
  secret: 1f7808138d114fbba8d38d31373d0667

product-config:
  financing-institutions:
    FastBank:
        enabled: true
        url: https://shop.stage.klix.app/api/FastBank
    SolidBank:
        enabled: true
        url: https://shop.stage.klix.app/api/SolidBank